services:
  # Web Server 01
  web01:
    build: .
    container_name: airbnb-web-01
    ports:
      - "8081:80"
    volumes:
      - ./web_static:/data/web_static/current
    networks:
      - airbnb_network
    environment:
      - SERVER_NAME=web-01

  # Web Server 02
  web02:
    build: .
    container_name: airbnb-web-02
    ports:
      - "8082:80"
    volumes:
      - ./web_static:/data/web_static/current
    networks:
      - airbnb_network
    environment:
      - SERVER_NAME=web-02

  # HAProxy Load Balancer
  haproxy:
    image: haproxy:2.8-alpine
    container_name: airbnb-lb-01
    ports:
      - "8080:80"
      - "8404:8404"  # Stats page
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - airbnb_network
    depends_on:
      - web01
      - web02

networks:
  airbnb_network:
    driver: bridge
